---
title: "Policy Reports"
permalink: /policy_reports/
---

<style>
  details{
    padding: 7pt;
  }
details[open]{
    background: #eeeeee;
}
</style>

<ol>
<li><a href="https://tobin.yale.edu/sites/default/files/files/C-19%20Articles/CARES-UI_identification_vF(1).pdf" target="_blank">Employment effects of unemployment insurance generosity during the pandemic</a> <i>(with Joseph Altonji, Zara Contractor, Ryan Hyangood, Ilse Lindenlaub, Costas Meghir, Cormac O'Dea, Dana Scott, Liana Wang, and Ebonya Washington)</i>, July 2020, Tobin Center for Economic Policy&mdash;Yale University.
<p style="font-size:11pt"> Media coverage: <a href="https://www.wsj.com/articles/federal-government-sent-workers-nearly-250-billion-in-600-a-week-jobless-aid-11597091188" target="_blank">Wall Street Journal</a>, <a href="https://www.wsj.com/articles/federal-government-sent-workers-nearly-250-billion-in-600-a-week-jobless-aid-11597091188" target="_blank">The Washington Post</a>, <a href="https://www.nytimes.com/2020/08/03/opinion/republicans-unemployed-coronavirus.html" target="_blank">The New York Times</a>, <a href="https://www.npr.org/transcripts/897836643" target="_blank">NPR</a>, and <a href="https://lucasfinamor.github.io/files/TobinCenter_UI_MediaCoverage.xlsx" target="_blank">131 others</a>
</p>
</li>
<p> </p>

<li><a href="https://tobin.yale.edu/sites/default/files/covid-19%20response/Tobin%20Center%20Report%20on%20Employment%20and%20Hours%20in%20Small%20Businesses%20Report%20final.pdf" target="_blank">The effects of the Coronavirus on hours of work of small business</a> <i>(with Joseph Altonji, Zara Contractor, Ryan Hyangood, Ilse Lindenlaub, Costas Meghir, Cormac O'Dea, Dana Scott, Liana Wang, and Ebonya Washington)</i>, June 2020, Tobin Center for Economic Policy&mdash;Yale University.
</li>

<p> </p>
<li><a href="https://www.google.com/books/edition/O_Brasil_sob_reforma/f1_RDwAAQBAJ?hl=en&gbpv=1&dq=O+Brasil+sob+reforma&printsec=frontcover" target="_blank">Uma nova rede de proteção social ao trabalhador</a> <i>(with André Portela de Souza, Ricardo Paes de Barros, Diana Coutinho, and Lycia Lima)</i>, in "O Brasil sob reforma" (book chapter), <i>1st edition 2020</i>. 
</li>

</ol>