---
title: "Research"
permalink: /research/
---

<style>
  details{
    padding: 7pt;
  }
details[open]{
    background: #eeeeee;
}
</style>

## Published Articles

<ol>
<li>"Labor Market Conditions and College Graduation: evidence from Brazil", <b>Economics of Education Review</b>, <i> 94C 102403</i> (2023).<span style="font-size:11pt;color:blue"> <span style="margin-left:10px"> <a href="https://doi.org/10.1016/j.econedurev.2023.102403" target="_blank">[Published Version]</a> </span>  <span style="margin-left:10px"> <a href="https://lucasfinamor.github.io/files/Finamor_2023_EER_manuscript.pdf" target="_blank">[Open Access Manuscript]</a> </span> </span>
<details> <summary style="font-size:10pt"><i>(Abstract)  </i></summary> 
<p style="font-size:10pt" align="justify"> 
College students graduating in a recession have been shown to face large and persistent negative effects on their earnings, health, and other outcomes. This paper investigates whether students delay graduation to avoid these effects. Using data on the universe of students in higher education in Brazil and leveraging variation in labor market conditions across time, space, and chosen majors, the paper finds that students in public institutions delay graduation to avoid entering depressed labor markets. A typical recession causes the on-time graduation rate to fall by 6.5% in public universities and there is no effect on private institutions. The induced delaying increases average graduation by 0.11 semesters, consistent with 1 out of 18 students delaying graduation by one year in public universities. The delaying effect is larger for students with higher scores, in higher-earnings majors, and from more advantaged backgrounds. This has important implications for the distributional impact of recessions. 
</p></details>
</li>

<li>
"Labor Market Trends and Unemployment Insurance Generosity During the Pandemic" <i>(with Dana Scott)</i>, <b>Economics Letters</b>, <i>199C, 109722</i> (2021). <span style="font-size:11pt;color:blue"> <span style="margin-left:10px"> <a href="https://doi.org/10.1016/j.econlet.2020.109722" target="_blank">[Published Version]</a> </span> <span style="margin-left:10px"> <a href="https://lucasfinamor.github.io/files/Finamor_Scott_2021_Manuscript.pdf" target="_blank">[Open Access Manuscript]</a> </span> </span>
<details> <summary style="font-size:10pt"><i>(Abstract)</i></summary> 
<p style="font-size:10pt" align="justify"> 
We test whether changes in unemployment insurance (UI) benefit generosity under the CARES Act in the US are associated with differential employment outcomes under the distinct conditions of the pandemic. While we observe a negative association between UI generosity and employment, we show that the relative employment gap arises before the Act was instituted, decreases in magnitude when the augmented benefits were in place, and does not change when the benefits expansion expires.
</p></details>
<span style="font-size:10pt"> Media coverage: <a href="https://www.cnbc.com/2021/01/12/600-unemployment-boost-backed-by-ron-wyden-not-a-work-disincentive.html" target="_blank">CNBC</a>, <a href="https://time.com/6078388/myth-generous-unemployment-benefits/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+time%2Fideas+%28TIME+Ideas%29" target="_blank">Time</a>, <a href="https://ca.news.yahoo.com/u-spends-less-nearly-every-164720852.html" target="_blank">Yahoo Canada</a>, <a href="https://newrepublic.com/article/160837/case-2000-checks" target="_blank">New Republic</a>, and <a href="https://plu.mx/plum/a/news?doi=10.1016/j.econlet.2020.109722&theme=plum-sciencedirect-theme&hideUsage=true" target="_blank">4 others</a>
</span>
</li>
</ol>

</br>

## Working Papers

<ol>
<li>"Labor Market Informality, Risk, and Insurance", <i>September 2025</i>. <span style="font-size:11pt;color:blue">  <span style="margin-left:10px"> <a href="https://lucasfinamor.github.io/files/Finamor_Lucas_JMP.pdf" target="_blank">[Manuscript]</a> </span>   </span>
<details> <summary style="font-size:10pt"><i>(Abstract) </i></summary> 
<p style="font-size:10pt" align="justify"> 
  Distinct working arrangements offer different prospects for workers. Formal employment provides insurance requiring contributions and taxes. Informal and self-employment lack insurance but offer faster exits from unemployment. Workers face complex tradeoffs involving present and future risks, insurance, liquidity, and earnings.
    To understand how employment decisions depend on risk, savings,  and insurance, I develop a life-cycle model of employment and savings in a frictional search environment. I estimate the model exploiting linked longitudinal survey and administrative Chilean data and policy reforms. 
    Workers attribute substantial value to the insurance and stability provided by formal jobs: informal employees would give up one-third of their net earnings to formalize their jobs. At the same time, informal opportunities insure workers against unemployment risk. 
    Counterfactual policy analyses reveal that ignoring risk aversion and the full insurance bundle embedded in formal employment leads to biased responses to social security reforms.
    The findings highlight that both formality and informality provide distinct forms of insurance, and that effective policy design requires accounting for the dynamic tradeoffs workers face over the life cycle.
</p></details>
</li>

<li> "Youth Subjective Life Expectancy and Early Labor Market Choices", <i>May 2025</i>. R&R Demography. <span style="font-size:11pt;color:blue">  <span style="margin-left:10px"> <a href="https://lucasfinamor.github.io/files/finamor_youthSLE.pdf" target="_blank">[Manuscript]</a> </span>  </span>
<details> <summary style="font-size:10pt"><i>(Abstract)</i></summary> 
<p style="font-size:10pt" align="justify"> The literature has documented how subjective life expectancy (SLE) is strongly associated with savings and retirement outcomes for those nearing retirement. This paper assesses whether SLE matters when young individuals make consequential career decisions at the labor market entrance. Exploring survey and administrative data from Chile, I show how individuals aged 18--26 with one standard deviation higher SLE have about 5% higher pension wealth 15 years later. In a pension system based on individual capitalization accounts, contributions made early in the career compound for longer and are therefore valuable. I employ different empirical strategies, including exploiting cross-sectional variation in SLE, longitudinal individual fixed-effects approach, and instrumental variables, exploring health and death of family members. All yield similar results. 
</p>
</details>
</li>

<li> "Long-term effects of a public school management program" <i>(with <a href="https://sites.google.com/site/brunoferman" target="_blank">Bruno Ferman</a>, André Portela Souza, and Geraldo Silva Filho)</i>, <i>April 2025</i>. <span style="font-size:11pt;color:blue">  <span style="margin-left:10px"> <a href="https://lucasfinamor.github.io/files/PJF_paper.pdf" target="_blank">[Manuscript]</a> </span>  </span>
<details> <summary style="font-size:10pt"><i>(Abstract)</i></summary> 
<p style="font-size:10pt" align="justify"> While a substantial body of research documents a positive correlation between school management practices and student outcomes, experimental evidence on their causal effects --- particularly over the long term --- remains limited. We exploit the randomized implementation of "Jovem de Futuro,'' a management program implemented in Brazilian public high schools. Drawing on rich administrative data, we follow students' educational and labor market trajectories over fifteen years. We find short-term improvements in test scores and high school completion. In the long run, however, the program yields null to modest effects on college enrollment and graduation, labor market participation, and earnings. 
</p>

</details>
</li>

<li>"There must be an error here! Experimental evidence on coding errors' biases" <i>(with <a href="https://sites.google.com/site/brunoferman" target="_blank">Bruno Ferman</a>)</i>. <span style="font-size:11pt;color:blue">  <span style="margin-left:10px"> <a href="https://lucasfinamor.github.io/files/CodingBias.pdf" target="_blank">[Manuscript]</a> </span>  </span>
<details> <summary style="font-size:10pt"><i>(Abstract)</i></summary> 
<p style="font-size:10pt" align="justify"> 
Quantitative research relies heavily on coding, and coding errors are relatively common even in published research.  In this paper, we examine whether individuals are more or less likely to check their code depending on the results they obtain. We test this hypothesis in a randomized experiment embedded in the recruitment process for research positions at a large international economic organization. In a coding task designed to assess candidates' programming abilities, we randomize whether participants obtain an expected or unexpected result if they commit a simple coding error. We find that individuals are 20% more likely to detect coding errors when they lead to unexpected results. This asymmetry in error detection depending on the results they generate suggests that coding errors may lead to biased findings in scientific research. </p>
</p> 
</details>
</li>

<li>
"School closures and educational path: how the Covid-19 pandemic affected transitions to college" <i>(with <a href="https://sites.google.com/site/festevang/" target="_blank"> Fernanda Estevan</a>)</i>, <i>September 2022</i>. <span style="font-size:11pt;color:blue">  <span style="margin-left:10px"> <a href="https://arxiv.org/pdf/2210.00138.pdf" target="_blank">[Manuscript]</a> </span></span>
<details> <summary style="font-size:10pt"><i>(Abstract)  </i></summary> 
<p style="font-size:10pt" align="justify"> We investigate the impact of the Covid-19 pandemic on the transition between high school and college in Brazil. Using microdata from the universe of students that applied to a selective university, we document how the Covid-19 shock increased enrollment for students in the top 10% high-quality public and private high schools. This increase comes at the expense of graduates from relatively lower-quality schools. Furthermore, this effect is entirely driven by applicants who were at high school during the Covid pandemic. The effect is large and completely offsets the gains in student background diversity achieved by a bold quota policy implemented years before Covid. These results suggest that not only students from underprivileged backgrounds endured larger negative effects on learning during the pandemic, but they also experienced a stall in their educational paths.
</p></details>
</li>

<li>"Are Public Schools in Developing Countries Ready to Integrate EdTech into Regular Instruction?" <i>(with <a href="https://sites.google.com/site/brunoferman" target="_blank">Bruno Ferman</a> and Lycia Lima)</i>, <i>March 2022</i>. <span style="font-size:11pt;color:blue"> <span style="margin-left:10px"> <a href="https://mpra.ub.uni-muenchen.de/109063/1/MPRA_paper_109063.pdf" target="_blank">[Manuscript]</a> </span> </span>
<details> <summary style="font-size:10pt"><i>(Abstract)  </i></summary> 
<p style="font-size:10pt" align="justify"> We study the impacts of a program that introduced a computer-assisted learning platform into regular math classes using a randomized control trial in Brazilian primary public schools. Once a week, teachers would take their students to the school's computer lab and teach using a dynamically adaptive platform, instead of their standard math classes. We find no average treatment effect on students' math proficiency. However, we find positive effects of the program on measures of attitudes towards math. Moreover, we find suggestive evidence that the program may have positive effects on proficiency when infrastructure is better, so that it can be implemented using one computer per student. These results highlight the implementation challenges associated with education technology interventions in developing countries.
</p></details>
</li>


</ol>

</br>


